'use strict';
/* ================================================================
   TrueLift Coach — catalogo.js  (GENERADO desde mi_rutina_truelift.xlsx
   y los planMod de los JSON de TrueLift; no editar a mano salvo
   OBJETIVOS_GRUPO, que es el criterio de semáforo del planificador)
   ================================================================ */

// Patrones de la plantilla (columna A de "Listas")
const CAT_PATRONES = [
 "(Ninguno)",
 "Empuje horizontal",
 "Empuje inclinado",
 "Aislamiento",
 "Tirón vertical",
 "Tirón horizontal",
 "Empuje vertical",
 "Deltoide posterior",
 "Estabilidad escapular",
 "Punto débil opcional",
 "Rodilla",
 "Unilateral",
 "Bisagra",
 "Flexión de rodilla",
 "Glúteo",
 "Glúteo medio",
 "Gemelo",
 "Core"
];

// Ejercicios disponibles por patrón (rangos con nombre de la plantilla)
const CAT_LISTAS = {
 "Empuje horizontal": [
  "Press banca con barra",
  "Flexiones",
  "Press banca con mancuernas",
  "Press banca en Smith",
  "Press de pecho en máquina",
  "Press en máquina convergente",
  "Press banca declinado con barra",
  "Press de pecho unilateral en máquina"
 ],
 "Empuje inclinado": [
  "Press inclinado con mancuernas",
  "Aperturas inclinadas con mancuernas",
  "Press inclinado con barra",
  "Press inclinado en Smith",
  "Press inclinado en máquina",
  "Press inclinado en máquina convergente",
  "Press inclinado con mancuernas agarre neutro"
 ],
 "Aislamiento": [
  "Curl en polea",
  "Elevación lateral en polea",
  "Extensión de cuádriceps",
  "Extensión en cuerda en polea",
  "Pec deck / polea cruzada",
  "Aductores en máquina",
  "Aperturas con mancuernas en banco plano",
  "Aperturas en polea de pie",
  "Cruce de poleas",
  "Curl con barra",
  "Curl con barra Z",
  "Curl con mancuernas",
  "Curl concentrado con mancuerna",
  "Curl de bíceps en máquina",
  "Curl en cuerda en polea",
  "Curl inclinado con mancuernas",
  "Curl martillo con mancuernas",
  "Curl predicador en máquina",
  "Elevación lateral con mancuernas",
  "Elevación lateral en máquina",
  "Elevación lateral inclinado en banco",
  "Extensión de cuádriceps unilateral",
  "Extensión en polea con barra",
  "Extensión por encima con mancuerna o barra Z",
  "Fondos en máquina",
  "Fondos en paralelas",
  "Patada de tríceps en polea",
  "Press francés con mancuernas o barra Z",
  "Sentadilla sissy",
  "Curl bayesiano en polea",
  "Curl predicador con barra Z",
  "Extensión de tríceps con barra recta en polea",
  "Extensión unilateral de tríceps en polea",
  "Elevación lateral unilateral en polea",
  "Extensión de tríceps en máquina"
 ],
 "Tirón vertical": [
  "Dominada agarre prono",
  "Dominada agarre neutro",
  "Dominada asistida en máquina",
  "Jalón al pecho agarre neutro abierto",
  "Jalón al pecho agarre neutro cerrado",
  "Jalón al pecho agarre prono",
  "Jalón al pecho agarre supino",
  "Jalón al pecho en máquina",
  "Pullover en polea",
  "Dominada agarre supino",
  "Jalón unilateral en polea",
  "Jalón al pecho agarre ancho"
 ],
 "Tirón horizontal": [
  "Remo con barra inclinado",
  "Remo Pendlay con barra",
  "Remo con mancuerna apoyado",
  "Remo en T en máquina",
  "Remo en máquina con apoyo de pecho",
  "Remo pecho apoyado en banco inclinado",
  "Remo sentado en polea",
  "Remo unilateral con mancuerna",
  "Remo unilateral en polea",
  "Remo invertido",
  "Remo en máquina Hammer",
  "Remo en polea baja agarre amplio"
 ],
 "Empuje vertical": [
  "Press militar de pie con barra",
  "Press Arnold con mancuernas",
  "Press de hombro en máquina",
  "Press militar sentado con barra",
  "Press sentado con mancuernas",
  "Press militar con mancuernas de pie",
  "Press en Smith sentado",
  "Press landmine a una mano"
 ],
 "Deltoide posterior": [
  "Face pull en polea",
  "Pájaros con mancuernas en banco inclinado",
  "Pájaros en máquina",
  "Pájaros en polea",
  "Pec deck inverso",
  "Face pull con cuerda alto",
  "Pájaros sentado con mancuernas"
 ],
 "Estabilidad escapular": [
  "Face pull suave en polea",
  "Pull-apart con banda",
  "Rotación externa con mancuerna",
  "Rotación externa en polea",
  "Elevaciones Y en banco inclinado",
  "Flexiones escapulares",
  "Wall slides"
 ],
 "Punto débil opcional": [
  "Elevación lateral ligera en polea",
  "Elevación frontal con mancuernas",
  "Elevación lateral ligera con mancuernas",
  "Elevación lateral en máquina",
  "Curl en cuerda en polea",
  "Extensión en cuerda en polea",
  "Gemelo sentado",
  "Crunch en máquina"
 ],
 "Rodilla": [
  "Sentadilla con barra",
  "Hack squat en máquina",
  "Prensa 45°",
  "Prensa 45° pies medios",
  "Sentadilla en Smith",
  "Sentadilla española",
  "Sentadilla goblet con mancuerna",
  "Sentadilla frontal con barra",
  "Prensa horizontal",
  "Sentadilla pendular"
 ],
 "Unilateral": [
  "Sentadilla búlgara en Smith",
  "Sentadilla búlgara con mancuernas",
  "Sentadilla dividida estática",
  "Step-up al cajón con mancuernas",
  "Zancada caminando con mancuernas",
  "Zancada con mancuernas",
  "Zancada atrás con mancuernas",
  "Sentadilla búlgara con barra",
  "Step-up en Smith"
 ],
 "Bisagra": [
  "Peso muerto rumano con barra",
  "Buenos días con barra",
  "Hiperextensión 45°",
  "Peso muerto a una pierna con mancuerna",
  "Peso muerto convencional con barra",
  "Peso muerto piernas rígidas Dead Stop",
  "Peso muerto rumano con mancuernas",
  "Peso muerto sumo con barra",
  "Peso muerto con barra hexagonal",
  "Pull-through en polea"
 ],
 "Flexión de rodilla": [
  "Curl femoral tumbado",
  "Curl femoral de pie unilateral",
  "Curl femoral sentado",
  "Curl nórdico asistido",
  "Curl femoral con mancuerna",
  "Curl femoral deslizante",
  "Curl femoral en fitball"
 ],
 "Glúteo": [
  "Hip thrust con barra",
  "Hip thrust a una pierna",
  "Hip thrust en máquina",
  "Patada de glúteo en polea",
  "Puente de glúteo con barra",
  "Hip thrust en Smith",
  "Extensión de cadera en máquina",
  "Pull-through en polea"
 ],
 "Glúteo medio": [
  "Abducción de cadera en máquina",
  "Abducción con banda sentado",
  "Abducción en polea",
  "Patada lateral en cuadrupedia",
  "Caminata lateral con banda",
  "Monster walk con banda",
  "Abducción de cadera tumbado de lado"
 ],
 "Gemelo": [
  "Gemelo de pie",
  "Gemelo a una pierna con mancuerna",
  "Gemelo en máquina Smith",
  "Gemelo en prensa",
  "Gemelo sentado",
  "Gemelo de pie en máquina",
  "Gemelo de pie en Smith",
  "Gemelo en prensa horizontal"
 ],
 "Core": [
  "Plancha frontal",
  "Crunch en máquina",
  "Crunch en polea",
  "Dead bug",
  "Elevación de piernas colgado",
  "Pallof press",
  "Plancha lateral",
  "Rotación de tronco en polea (woodchop)",
  "Rueda abdominal",
  "Crunch inverso",
  "Elevación de rodillas en silla romana",
  "Plancha con peso",
  "Bird dog"
 ]
};

// Grupo muscular de cada ejercicio (pares confirmados de planMod + clasificación)
const CAT_GRUPO_DE = {
 "Press banca con barra": "Pectoral",
 "Flexiones": "Pectoral",
 "Press banca con mancuernas": "Pectoral",
 "Press banca en Smith": "Pectoral",
 "Press de pecho en máquina": "Pectoral",
 "Press en máquina convergente": "Pectoral",
 "Press banca declinado con barra": "Pectoral",
 "Press de pecho unilateral en máquina": "Pectoral",
 "Press inclinado con mancuernas": "Pectoral",
 "Aperturas inclinadas con mancuernas": "Pectoral",
 "Press inclinado con barra": "Pectoral",
 "Press inclinado en Smith": "Pectoral",
 "Press inclinado en máquina": "Pectoral",
 "Press inclinado en máquina convergente": "Pectoral",
 "Press inclinado con mancuernas agarre neutro": "Pectoral",
 "Curl en polea": "Bíceps",
 "Elevación lateral en polea": "Hombro",
 "Extensión de cuádriceps": "Cuádriceps",
 "Extensión en cuerda en polea": "Tríceps",
 "Pec deck / polea cruzada": "Pectoral",
 "Aductores en máquina": "Isquios/glúteo",
 "Aperturas con mancuernas en banco plano": "Pectoral",
 "Aperturas en polea de pie": "Pectoral",
 "Cruce de poleas": "Pectoral",
 "Curl con barra": "Bíceps",
 "Curl con barra Z": "Bíceps",
 "Curl con mancuernas": "Bíceps",
 "Curl concentrado con mancuerna": "Bíceps",
 "Curl de bíceps en máquina": "Bíceps",
 "Curl en cuerda en polea": "Bíceps",
 "Curl inclinado con mancuernas": "Bíceps",
 "Curl martillo con mancuernas": "Bíceps",
 "Curl predicador en máquina": "Bíceps",
 "Elevación lateral con mancuernas": "Hombro",
 "Elevación lateral en máquina": "Hombro",
 "Elevación lateral inclinado en banco": "Hombro",
 "Extensión de cuádriceps unilateral": "Cuádriceps",
 "Extensión en polea con barra": "Tríceps",
 "Extensión por encima con mancuerna o barra Z": "Tríceps",
 "Fondos en máquina": "Tríceps",
 "Fondos en paralelas": "Tríceps",
 "Patada de tríceps en polea": "Tríceps",
 "Press francés con mancuernas o barra Z": "Tríceps",
 "Sentadilla sissy": "Cuádriceps",
 "Curl bayesiano en polea": "Bíceps",
 "Curl predicador con barra Z": "Bíceps",
 "Extensión de tríceps con barra recta en polea": "Tríceps",
 "Extensión unilateral de tríceps en polea": "Tríceps",
 "Elevación lateral unilateral en polea": "Hombro",
 "Extensión de tríceps en máquina": "Tríceps",
 "Dominada agarre prono": "Espalda",
 "Dominada agarre neutro": "Espalda",
 "Dominada asistida en máquina": "Espalda",
 "Jalón al pecho agarre neutro abierto": "Espalda",
 "Jalón al pecho agarre neutro cerrado": "Espalda",
 "Jalón al pecho agarre prono": "Espalda",
 "Jalón al pecho agarre supino": "Espalda",
 "Jalón al pecho en máquina": "Espalda",
 "Pullover en polea": "Espalda",
 "Dominada agarre supino": "Espalda",
 "Jalón unilateral en polea": "Espalda",
 "Jalón al pecho agarre ancho": "Espalda",
 "Remo con barra inclinado": "Espalda",
 "Remo Pendlay con barra": "Espalda",
 "Remo con mancuerna apoyado": "Espalda",
 "Remo en T en máquina": "Espalda",
 "Remo en máquina con apoyo de pecho": "Espalda",
 "Remo pecho apoyado en banco inclinado": "Espalda",
 "Remo sentado en polea": "Espalda",
 "Remo unilateral con mancuerna": "Espalda",
 "Remo unilateral en polea": "Espalda",
 "Remo invertido": "Espalda",
 "Remo en máquina Hammer": "Espalda",
 "Remo en polea baja agarre amplio": "Espalda",
 "Press militar de pie con barra": "Hombro",
 "Press Arnold con mancuernas": "Hombro",
 "Press de hombro en máquina": "Hombro",
 "Press militar sentado con barra": "Hombro",
 "Press sentado con mancuernas": "Hombro",
 "Press militar con mancuernas de pie": "Hombro",
 "Press en Smith sentado": "Hombro",
 "Press landmine a una mano": "Hombro",
 "Face pull en polea": "Hombro",
 "Pájaros con mancuernas en banco inclinado": "Hombro",
 "Pájaros en máquina": "Hombro",
 "Pájaros en polea": "Hombro",
 "Pec deck inverso": "Hombro",
 "Face pull con cuerda alto": "Hombro",
 "Pájaros sentado con mancuernas": "Hombro",
 "Face pull suave en polea": "Hombro",
 "Pull-apart con banda": "Hombro",
 "Rotación externa con mancuerna": "Hombro",
 "Rotación externa en polea": "Hombro",
 "Elevaciones Y en banco inclinado": "Hombro",
 "Flexiones escapulares": "Hombro",
 "Wall slides": "Hombro",
 "Elevación lateral ligera en polea": "Hombro",
 "Elevación frontal con mancuernas": "Hombro",
 "Elevación lateral ligera con mancuernas": "Hombro",
 "Gemelo sentado": "Gemelo",
 "Crunch en máquina": "Core",
 "Sentadilla con barra": "Cuádriceps",
 "Hack squat en máquina": "Cuádriceps",
 "Prensa 45°": "Cuádriceps",
 "Prensa 45° pies medios": "Cuádriceps",
 "Sentadilla en Smith": "Cuádriceps",
 "Sentadilla española": "Cuádriceps",
 "Sentadilla goblet con mancuerna": "Cuádriceps",
 "Sentadilla frontal con barra": "Cuádriceps",
 "Prensa horizontal": "Cuádriceps",
 "Sentadilla pendular": "Cuádriceps",
 "Sentadilla búlgara en Smith": "Cuádriceps",
 "Sentadilla búlgara con mancuernas": "Cuádriceps",
 "Sentadilla dividida estática": "Cuádriceps",
 "Step-up al cajón con mancuernas": "Cuádriceps",
 "Zancada caminando con mancuernas": "Cuádriceps",
 "Zancada con mancuernas": "Cuádriceps",
 "Zancada atrás con mancuernas": "Cuádriceps",
 "Sentadilla búlgara con barra": "Cuádriceps",
 "Step-up en Smith": "Cuádriceps",
 "Peso muerto rumano con barra": "Isquios/glúteo",
 "Buenos días con barra": "Isquios/glúteo",
 "Hiperextensión 45°": "Isquios/glúteo",
 "Peso muerto a una pierna con mancuerna": "Isquios/glúteo",
 "Peso muerto convencional con barra": "Isquios/glúteo",
 "Peso muerto piernas rígidas Dead Stop": "Isquios/glúteo",
 "Peso muerto rumano con mancuernas": "Isquios/glúteo",
 "Peso muerto sumo con barra": "Isquios/glúteo",
 "Peso muerto con barra hexagonal": "Isquios/glúteo",
 "Pull-through en polea": "Isquios/glúteo",
 "Curl femoral tumbado": "Isquios/glúteo",
 "Curl femoral de pie unilateral": "Isquios/glúteo",
 "Curl femoral sentado": "Isquios/glúteo",
 "Curl nórdico asistido": "Isquios/glúteo",
 "Curl femoral con mancuerna": "Isquios/glúteo",
 "Curl femoral deslizante": "Isquios/glúteo",
 "Curl femoral en fitball": "Isquios/glúteo",
 "Hip thrust con barra": "Isquios/glúteo",
 "Hip thrust a una pierna": "Isquios/glúteo",
 "Hip thrust en máquina": "Isquios/glúteo",
 "Patada de glúteo en polea": "Isquios/glúteo",
 "Puente de glúteo con barra": "Isquios/glúteo",
 "Hip thrust en Smith": "Isquios/glúteo",
 "Extensión de cadera en máquina": "Isquios/glúteo",
 "Abducción de cadera en máquina": "Isquios/glúteo",
 "Abducción con banda sentado": "Isquios/glúteo",
 "Abducción en polea": "Isquios/glúteo",
 "Patada lateral en cuadrupedia": "Isquios/glúteo",
 "Caminata lateral con banda": "Isquios/glúteo",
 "Monster walk con banda": "Isquios/glúteo",
 "Abducción de cadera tumbado de lado": "Isquios/glúteo",
 "Gemelo de pie": "Gemelo",
 "Gemelo a una pierna con mancuerna": "Gemelo",
 "Gemelo en máquina Smith": "Gemelo",
 "Gemelo en prensa": "Gemelo",
 "Gemelo de pie en máquina": "Gemelo",
 "Gemelo de pie en Smith": "Gemelo",
 "Gemelo en prensa horizontal": "Gemelo",
 "Plancha frontal": "Core",
 "Crunch en polea": "Core",
 "Dead bug": "Core",
 "Elevación de piernas colgado": "Core",
 "Pallof press": "Core",
 "Plancha lateral": "Core",
 "Rotación de tronco en polea (woodchop)": "Core",
 "Rueda abdominal": "Core",
 "Crunch inverso": "Core",
 "Elevación de rodillas en silla romana": "Core",
 "Plancha con peso": "Core",
 "Bird dog": "Core"
};

// Grupo por patrón (para ejercicios personalizados que no estén en el catálogo)
const CAT_PATRON_GRUPO = {
 "Empuje horizontal": "Pectoral",
 "Empuje inclinado": "Pectoral",
 "Empuje vertical": "Hombro",
 "Tirón vertical": "Espalda",
 "Tirón horizontal": "Espalda",
 "Deltoide posterior": "Hombro",
 "Estabilidad escapular": "Hombro",
 "Rodilla": "Cuádriceps",
 "Unilateral": "Cuádriceps",
 "Bisagra": "Isquios/glúteo",
 "Flexión de rodilla": "Isquios/glúteo",
 "Glúteo": "Isquios/glúteo",
 "Glúteo medio": "Isquios/glúteo",
 "Gemelo": "Gemelo",
 "Core": "Core"
};

// Descansos admitidos (min) y sistemas
const CAT_DESCANSOS = [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6];
const CAT_SISTEMAS = ['simple','doble'];

/* Criterio de volumen (series planificadas/semana por grupo) y frecuencia
   (días/semana que se estimula el grupo). Semáforo del planificador:
   verde dentro de [min,max]; ámbar hasta 25% fuera; rojo más allá. */
const OBJETIVOS_GRUPO = {
 "Pectoral": {
  "min": 10,
  "max": 20,
  "frec": 2
 },
 "Espalda": {
  "min": 10,
  "max": 20,
  "frec": 2
 },
 "Hombro": {
  "min": 8,
  "max": 20,
  "frec": 2
 },
 "Bíceps": {
  "min": 6,
  "max": 16,
  "frec": 2
 },
 "Tríceps": {
  "min": 6,
  "max": 16,
  "frec": 2
 },
 "Cuádriceps": {
  "min": 8,
  "max": 18,
  "frec": 2
 },
 "Isquios/glúteo": {
  "min": 8,
  "max": 18,
  "frec": 2
 },
 "Gemelo": {
  "min": 6,
  "max": 16,
  "frec": 2
 },
 "Core": {
  "min": 0,
  "max": 12,
  "frec": 1
 }
};

const ORDEN_GRUPOS = ['Pectoral','Espalda','Hombro','Bíceps','Tríceps',
                      'Cuádriceps','Isquios/glúteo','Gemelo','Core'];
